Feature/r18 roadmap
pxblue/pxb-database pull request #25
Opened 2020-09-29 16:56 UTC by emclaug2

#### Changes proposed in this Pull Request:
- Add R18 roadmap data onto the existing R17 roadmap

It seems like the easiest approach for updating these roadmaps to just continue to aggregate the new items onto a copy/pasted version of the old roadmap. 

The R17 roadmap did not have any of the R16 items available (for historic data). 
I think it would be a good idea to have R16 data added into the mix.  Thoughts?

![image](https://user-images.githubusercontent.com/6538289/94589296-1bfc6900-0253-11eb-9b99-24649304567b.png)

![image](https://user-images.githubusercontent.com/6538289/94589371-2fa7cf80-0253-11eb-8941-51fd136df18d.png)

![image](https://user-images.githubusercontent.com/6538289/94589436-40584580-0253-11eb-9d37-8f1f72c55eff.png)

2020-09-29 16:57 UTC, emclaug2 commented
Should I just delete all deferred items going into R18?  Components aren't a priority in R18 and probably won't get done.

2020-09-30 10:44 UTC, joebochill requested changes
Couple comments
- If I look at R17 in the dropdown, I don't see the items that were deferred. If this is meant to be the single source of truth for each release, there should be a record of what was deferred, even if it doesn't get included in the next release.
- Can we rename the release dropdown items to include the quarter — `R18 (4Q20)`

For the R18 items:
- Add items to Figma components (dialogs, menus, side sheets)
- Figma Patterns: include one item for each story we have on the backlog for these (almost one for each pattern)
- Specify the upcoming patterns for doc-it: Navigation, Page Layout, Visualizations

Add some stretch goals for R19. Things that we might pick up if we have time (like the new components, etc.). These don't have to be as fleshed out as the R18 stuff.

2020-09-30 15:12 UTC, emclaug2 commented
> * Can we rename the release dropdown items to include the quarter — `R18 (4Q20)`

Yep I'll make this change as a part of a doc-it PR

2020-09-30 15:28 UTC, huayunh commented
FYI there are a few extra DSM components that might be worth adding to the R17 roadmap. Those items are pending review this afternoon. 

pxblue patterns:
- Progress Indicators
- Pagers
- Panels

some more material things (but pxblue-ized):
- Switches
- Avatars
- Backdrop

2020-09-30 15:43 UTC, emclaug2 commented
> FYI there are a few extra DSM components that might be worth adding to the R17 roadmap. Those items are pending review this afternoon.
> 
> pxblue patterns:
> 
> * Progress Indicators
> * Pagers
> * Panels
> * Dropdown Toolbar (as a minor tweak to the existing app bar)
> 
> some more material things (but pxblue-ized):
> 
> * Switches
> * Avatars
> * Backdrop

Is there any reason why we need this level of specificity?  

All previous quarters kept it generic.  Adding this level of specify will cause issues if we don't get everything in the description complete.  How would we mark one design pattern as deferred if we don't complete it this quarter?  

R17 description: 
`
Design Patterns
New format and content for design patterns
`

Should I split the R18 description into multiple items?

I prefer keeping it as vague as the R17 description.

2020-09-30 15:58 UTC, joebochill commented
> I prefer keeping it as vague as the R17 description.

Which item are you talking about? Huayun is talking about Figma Stickersheet Components, not design patterns. I would agree for the design patterns on doc-it we can keep it generic like R17. For the components/patterns the advantage of splitting them up is that we can update the status more frequently (we can mark things as complete on an individual basis rather than requiring everything to be complete...and we can defer individual items if needed). I would be okay with doing some reasonable grouping/combination, but I would lean away from doing them all in a single line item.

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +        "description": "Design templates for Login and Registration workflows",
The descriptions of all of these should follow the same pattern:
e.g.:
`Designer templates / examples for ...`

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +        "author": "PX Blue"
I think all of these other line items are templates right? Can we remove this line item?

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +      },
We could probably leave this one out since it's already in the DSM as a component

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +      },
Might be able to leave this one out as well since it's in DSM as a component already

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +      },
Another one we can probably leave out - covered by components

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +        "author": "PX Blue"
This one is already covered by "Login and Registration"

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +        "description": "Full compatibility with version 10 of the @angular component library",
```suggestion
        "description": "Full compatibility with version 10 of Angular",
```

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +        "author": "PX Blue"
Collapsible Appbar for 2021?

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +      }
Collapsible appbar 2021?
Pager 2021?
Expandable bottomsheet 2021? Maybe not this one.

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +        "description": "Design pattern updates for navigation, page layout, and visualizations",
This description I think you can keep generic, per your question

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +    ]
Updated Iconography page Q4?

2020-09-30 16:08 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +      }
2021 new examples for mobile (the ones we're currently missing)?

2020-09-30 16:54 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +        "author": "PX Blue"
You're right, this ain't needed anymore.

2020-09-30 16:54 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +        "description": "Design templates for Login and Registration workflows",
Will do!

2020-09-30 16:54 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +      },
Removed!

2020-09-30 16:55 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +      },
Removed!

2020-09-30 16:55 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +        "author": "PX Blue"
Oh right, this is removed now/

2020-09-30 16:56 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +        "description": "Full compatibility with version 10 of the @angular component library",
Got it!

2020-09-30 16:57 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +      }
I'm not include the expandable bottomsheet, not sure what that is.  Others are added now!

2020-09-30 16:58 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +        "description": "Design pattern updates for navigation, page layout, and visualizations",
Reverted 👍

2020-09-30 16:59 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +    ]
Got it!

2020-09-30 17:02 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +      }
Added for UserMenu, Drawer, and more

2020-09-30 17:02 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +      },
Removed

2020-09-30 17:02 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +        "author": "PX Blue"
You got it!

2020-09-30 17:36 UTC, joebochill approved these changes

2020-09-30 17:36 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +      }
Material-UI already has a "Mobile Stepper" so we probably won't need to build this for React

2020-09-30 17:36 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +      }
You can move it into the RN section though

2020-09-30 17:36 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +        ]
This would be for the MonoRepo...so the mssing examples are things like I18N, Forms, etc.

2020-09-30 17:36 UTC, joebochill commented on deployed/doc-it/R18Roadmap.json
> +        ]
And maybe Q1 2021 instead of Q4

2020-09-30 18:40 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +      }
Moved 👍

2020-09-30 18:41 UTC, emclaug2 commented on deployed/doc-it/R18Roadmap.json
> +        ]
Got it

2020-09-30 18:42 UTC, merged