Update roadmpa sprint 2 Q1
pxblue/pxb-database pull request #43
Opened 2021-01-29 18:19 UTC by emclaug2

#### Changes proposed in this Pull Request:
- Sprint 2 Updates

2021-01-29 18:51 UTC, jeffvg approved these changes

2021-01-29 18:52 UTC, joebochill reviewed
- Angular CLI templates are finished too

2021-01-29 18:52 UTC, joebochill commented on deployed/doc-it/R19Roadmap.json
> +        "status": "pre-release",
still backlog

2021-01-29 18:52 UTC, joebochill commented on deployed/doc-it/R19Roadmap.json
> +        "status": "in-progress",
you can call this pre-release...i'm pretty sure it'll go out in beta today

2021-01-29 20:06 UTC, huayunh commented on deployed/doc-it/R19Roadmap.json
>          "description": "Designer templates / examples for searching and filtering",
We don’t really do “filtering” (besides like some simple drop downs) can we change the name of this item 🙈

2021-02-01 12:06 UTC, joebochill requested changes
See comments.

2021-02-01 13:50 UTC, emclaug2 commented on deployed/doc-it/R19Roadmap.json
> +        "status": "in-progress",
This is now pre-release.

2021-02-01 13:52 UTC, emclaug2 commented
Comment changes should be addressed now.

2021-02-01 13:54 UTC, joebochill reviewed
You need to update the search pattern description for the 2021 entry. Also Angular CLI templates are 'finished'.

2021-02-01 13:57 UTC, joebochill approved these changes

2021-02-01 13:57 UTC, merged

2021-02-01 13:57 UTC, emclaug2 commented
> You need to update the search pattern description for the 2021 entry. Also Angular CLI templates are 'finished'.

Good catch, this is updated now.  I can see why splitting out the roadmap into separate files would be a good refactor now.